### ISSUE TITLE
nothing is working

### ISSUE THREAD

**Issue by VelikiySebas** [kuff/discordify#7] opened 2020-05-30 12:16 UTC
yesterday dispatcher stop working idk why 
![Screenshot_6](https://user-images.githubusercontent.com/60559667/83327960-83e07a00-a288-11ea-8176-75bd7dd9545f.png)
`internal/validators.js:117
throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
at validateString (internal/validators.js:117:11)
at Url.parse (url.js:159:3)
at Object.urlParse [as parse] (url.js:154:13)
at doDownload (/home/container/node_modules/miniget/dist/index.js:90:28)
at processTicksAndRejections (internal/process/task_queues.js:79:11) {
code: 'ERR_INVALID_ARG_TYPE'
/entrypoint.sh: line 12: ./usr/local/bin/node: No such file or directory`

**Comment by kuff** [comment] 2020-05-30 12:26
Thank you so much!

Can confirm the error is reproducible on my end and I will be looking into it.

Expect further updates in this thread.

**Comment by kuff** [comment] 2020-05-30 13:11
The bug is now fixed (at least on my end).

The bug was caused by an outdated dependency. You must therefore reinstall all dependencies to patch the bot.

From within your "discordify-master" directory:

1. Start by getting the latest dependency list with `git pull`.
2. Then remove the previously installed dependencies with `rm -r node_modules`.
3. Lastly, do `npm i` to reinstall.
4. Now try running the bot again.

Let me know if the issue persists and have a nice weekend!

**Comment by VelikiySebas** [comment] 2020-05-30 13:23
by the way, this version still have crashes while autoplay?

**Comment by kuff** [comment] 2020-05-30 13:32
Great!

Autoplay seems to be working fine for me. I will need more information to try and reproduce:

1. When did autoplay last crash for you?
2. Is it a particular video that makes it crash? A playlist?
3. Have you had the bot running for a while when it crashes?

Of course a printout of the error like the one you provided above would also be very helpful.

**Closed** 2020-05-30 15:20 UTC
